import Head from 'next/head'
import Hero from '../components/organisms/Hero'
import Reason from '../components/organisms/Reason'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Netbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Reason />
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
